[package]
name = "swayws"
version = "0.2.2"
edition = "2018"
license = "MIT"
description = "Sway workspace tool which allows easy moving of workspaces to and from outputs"
repository = "https://gitlab.com/w0lff/swayws"
exclude = [
    ".idea/*",
]

[dependencies]
structopt = "0.3.22"
swayipc = "2.7.2"
