[package]
name = "swayws"
version = "0.2.3"
edition = "2018"
license = "MIT"
description = "Sway workspace tool which allows easy moving of workspaces to and from outputs"
repository = "https://gitlab.com/w0lff/swayws"
exclude = [
    ".idea/*",
]

[dependencies]
clap = { version = "3.0.4", features = ["derive"] }
swayipc = "2.7.2"
